name: test
on:
  push:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
  pull_request:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version:
          - 'stable'
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install libvips
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libvips-dev \
            libvips-tools
      - run: nimble install -Y
      - run: nim c -r src/libvips.nim
      - run: nimble test